#! /bin/bash

# Erase any old executable files
rm *.out

echo "The current directory contains: "
ls 

# Compile serial.cpp
g++ -m64 -o serial.out serial.cpp

# Execute the program
./serial.out







